### ISSUE TITLE
Failure when writing XMLTV File

### ISSUE THREAD

**Issue by nickroberts** [alturismo/guide2go#5]
It looks like the update to the `guide2go` binary broke something.

When writing the xml file, it looks like some hardcoded path is referenced, so things blow up.

```shell
2024/03/21 22:25:21 [G2G  ] Create XMLTV File [/guide2go/lineup.xml]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6e17f5]

goroutine 1 [running]:
main.GetImageUrl({0xc00012a280?, 0x32?}, {0xc00027b200?, 0x1?}, {0xc008c425a0, 0x44})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/cache.go:592 +0x1f5
main.(*cache).GetIcon(0x0?, {0xc002e15b80, 0xa})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/cache.go:651 +0x305
main.getProgram({{0x0, 0x0}, {0x0, 0x0}, {0xc004b63df6, 0x6}, {0xc004b63e00, 0x8}, {0xc004b63e08, 0x7}, ...})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/xmltv.go:176 +0x99c
main.CreateXMLTV({0x7ffe781cfef4?, 0x7?})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/xmltv.go:86 +0xb18
main.(*SD).Update(0xc000146380, {0x7ffe781cfef4, 0xb})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/data.go:48 +0x1cc
main.Configure({0x7ffe781cfef4, 0xb})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/configure.go:110 +0x805
main.main()
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/main.go:38 +0x1dc
```

I got by this by manually downloading the previous version of the binary from this repo, but that is obviously not a permanent solution.

**Comment by gabort-snow** [comment]
I have the same issue.

2024/09/11 17:47:18 [G2G  ] Create XMLTV File [/guide2go/dsconfig.xml]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x6e17f5]

goroutine 1 [running]:
main.GetImageUrl({0xc00b4c0980?, 0x32?}, {0xc000365f80?, 0x1?}, {0xc00b92d630, 0x44})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/cache.go:592 +0x1f5
main.(*cache).GetIcon(0xc000133820?, {0xc00f6e9210, 0xa})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/cache.go:651 +0x305
main.getProgram({{0x0, 0x0}, {0x0, 0x0}, {0xc002580c36, 0x6}, {0xc002580c40, 0x8}, {0xc002580c48, 0x7}, ...})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/xmltv.go:176 +0x99c
main.CreateXMLTV({0x7fff122eceee?, 0x7?})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/xmltv.go:86 +0xb18
main.(*SD).Update(0xc0001a8380, {0x7fff122eceee, 0x17})
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/data.go:48 +0x1cc
main.main()
        C:/Users/alturismo/Desktop/guide2go-master/guide2go-master/main.go:47 +0x21a
